server:
  servlet:
    context-path: /league
  port: 8090

logging:
  level:
    org.springframework: ERROR

spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/leaguedb
    username: football-service
    password: football-service

